"""partial unique indexing

Revision ID: bd59332848cc
Revises: f8f8b25aa3cf
Create Date: 2026-10-10 18:38:45.359014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd59332848cc'
down_revision: Union[str, Sequence[str], None] = 'f8f8b25aa3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_one_accept_per_listing', 'deal_requests', ['listing_id'], unique=True, sqlite_where=sa.text("status='accepted'"), postgresql_where=sa.text("status='accepted'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_one_accept_per_listing', table_name='deal_requests', sqlite_where=sa.text("status='accepted'"), postgresql_where=sa.text("status='accepted'"))
    # ### end Alembic commands ###
