"""rename column create_at to created_at add

Revision ID: f8f8b25aa3cf
Revises: 8786fd1558d1
Create Date: 2026-09-29 18:48:47.542637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f8b25aa3cf'
down_revision: Union[str, Sequence[str], None] = '8786fd1558d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('listings', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('create_at', sa.DATETIME(), nullable=False))
    op.drop_column('listings', 'created_at')
    # ### end Alembic commands ###
